In [69]:
import numpy as np

#### Scaler / 0 Dimension Tensor

In [70]:
a = np.array(4)

In [71]:
a

array(4)

In [72]:
a.ndim

0

#### Vector / 1 Dimension Tensor

In [73]:
ar = np.array([1,2,3,4])

In [74]:
ar

array([1, 2, 3, 4])

1D Tensor is Vector but the len of the Vector decides what is the Vector Dimension. 

In this case, it is a 4D Vector and a 1D Tensor.


`Vectors are nothing but collection of Scalers`

In [75]:
ar.ndim

1

#### Matrices / 2 Dimension Tensor

In [76]:
arr = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [77]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

`Matrices are nothing but collection of Vectors`

In [78]:
arr.ndim

2

#### 3 Dimension Tensor

In [79]:
arrr = np.array([
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4],[1,2,3,4]]
])

In [80]:
arrr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

`3D Tensors are nothing but collection of Matrices`

In [81]:
arrr.ndim

3